# Base paths
ARR_BASE="${ARR_BASE:-$PWD}"
ARR_STACK_DIR="${ARR_STACK_DIR:-$ARR_BASE}"
ARR_DOCKER_DIR="${ARR_DOCKER_DIR:-$ARR_BASE/docker-data}"
ARRCONF_DIR="${ARRCONF_DIR:-$ARR_BASE/arrconf}"
DOWNLOADS_DIR="${DOWNLOADS_DIR:-$ARR_BASE/downloads}"
COMPLETED_DIR="${COMPLETED_DIR:-$ARR_BASE/completed}"
MEDIA_DIR="${MEDIA_DIR:-$ARR_BASE/media}"
TV_DIR="${TV_DIR:-$MEDIA_DIR/tv}"
MOVIES_DIR="${MOVIES_DIR:-$MEDIA_DIR/movies}"

# Defaults
TIMEZONE="${TIMEZONE:-Australia/Sydney}"
LAN_IP="${LAN_IP:-0.0.0.0}"
LOCALHOST_IP="${LOCALHOST_IP:-127.0.0.1}"

# Loopback and control hosts – default to localhost but configurable
GLUETUN_LOOPBACK_HOST="${GLUETUN_LOOPBACK_HOST:-127.0.0.1}"
GLUETUN_CONTROL_HOST="${GLUETUN_CONTROL_HOST:-127.0.0.1}"

# Control server port and API key
GLUETUN_CONTROL_PORT="${GLUETUN_CONTROL_PORT:-8000}"
GLUETUN_API_KEY="${GLUETUN_API_KEY:-}"

# Web ports (container-internal and host bind)
QBT_HTTP_PORT_CONTAINER="${QBT_HTTP_PORT_CONTAINER:-8080}"
QBT_HTTP_PORT_HOST="${QBT_HTTP_PORT_HOST:-8081}"
SONARR_PORT="${SONARR_PORT:-8989}"
RADARR_PORT="${RADARR_PORT:-7878}"
PROWLARR_PORT="${PROWLARR_PORT:-9696}"
BAZARR_PORT="${BAZARR_PORT:-6767}"
FLARESOLVERR_PORT="${FLARESOLVERR_PORT:-8191}"
