# Base paths
ARR_BASE="${ARR_BASE:-$PWD}"
ARR_STACK_DIR="${ARR_STACK_DIR:-$ARR_BASE}"
ARR_DOCKER_DIR="${ARR_DOCKER_DIR:-$ARR_BASE/docker-data}"
ARRCONF_DIR="${ARRCONF_DIR:-$ARR_BASE/arrconf}"
DOWNLOADS_DIR="${DOWNLOADS_DIR:-$ARR_BASE/downloads}"
COMPLETED_DIR="${COMPLETED_DIR:-$ARR_BASE/completed}"
MEDIA_DIR="${MEDIA_DIR:-$ARR_BASE/media}"
TV_DIR="${TV_DIR:-$MEDIA_DIR/tv}"
MOVIES_DIR="${MOVIES_DIR:-$MEDIA_DIR/movies}"

# Defaults
TIMEZONE="${TIMEZONE:-Australia/Sydney}"
LAN_IP="${LAN_IP:-0.0.0.0}"
